---
- # tasks file for services
- name: Creating EC2
  ec2:
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
      key_name: "{{ec2_key_name}}"
      wait: true
      region: "{{ec2_region}}"
      instance_type: "{{ec2_instance_type}}"
      image: "{{ec2_image}}"
  register: ec2
 # Creating 'webservers' and adding to /etc/ansible/hosts
- name: Add the newly created host so that we can further contact it
  add_host:
    name: "{{ item.public_ip }}"
    groups: webservers
  with_items: "{{ ec2.instances }}" 
# importing ssh role
# registered var: ec2 --> ssh role
- name: Pass EC2 to SSH
  include_role:
      name: ssh_service
  vars:
       rolevar1: ec2
# - name: Stop EC2 instance
  # ec2:
      # aws_access_key: "{{aws_access_key}}"
      # aws_secret_key: "{{aws_secret_key}}"
      # # key_name: "{{ec2_key_name}}"
      # # wait: true
      # region: "{{ec2_region}}"
      # instance_ids: "{{ec2.instance_ids}}"
      # state: stopped
      
 # Start instance
 # - name: Start Instance
   # ec2:
      # aws_access_key: "{{aws_access_key}}"
      # aws_secret_key: "{{aws_secret_key}}"
      # key_name: "{{ec2_key_name}}"
      # wait: true
      # region: "{{ec2_region}}"
      # instance_ids: "{{ec2.instance_ids}}"
      # state: running
       
 # - name: Terminate Instance
   # ec2:
       # aws_access_key: "{{aws_access_key}}"
       # aws_secret_key: "{{aws_secret_key}}"
       # key_name: "{{ec2_key_name}}"
       # wait: true
       # region: "{{ec2_region}}"
       # state: absent
       # instance_ids: "{{ec2.instance_ids}}"