---
# tasks file for create_sec_group
- name: Create a security group
  ec2_group:
    name: "{{ec2_security_group}}"
    description: The webservers security group
    region: "{{ec2_region}}"
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    rules:
    - proto: tcp
      ports:
        - 22
      cidr_ip: 0.0.0.0/0
    rules_egress:
    - proto: all
      cidr_ip: 0.0.0.0/0 