---
# tasks file for ssh_service
- name: Verify SSH state is started
# Wait for SSH connection to be started
  wait_for:
    host: "{{item.public_ip}}"
    port: 22
    state: started
  loop: "{{ec2.instances}}"
  
# - name: Include deploy
  # include_role:
    # name: deploy_apache
  # vars:
       # rolevar1: ec2
    
