---
# tasks file for ssh_service
- name: SSH into EC2 Instance
  remote_user: ec2-user
# Wait for SSH connection
  wait_for:
    host: "{{item.public_ip}}"
    port: 22
    timeout: 30
    state: started
  with_items: "{{ec2.instances}}"
    