---
- name: Create EC2 instance
  vars_files:
          - aws_keys.yml 
  hosts: localhost
  gather_facts: false
  
  remote_user: ec2-user
  roles:
   - create_sec_group
   #- services
     
 # - hosts: webservers
  # remote_user: ubuntu
  # become: yes
  # gather_facts: no
  # vars_files:
    # - aws_keyfile.yml
  # roles:
    # - apache 