---
- name: Create EC2 instance and SSH
  vars_files:
    - aws_keys.yml 
  hosts: localhost
  connection: local #makes local connection
  gather_facts: false
  roles:
    - create_sec_group
    - ec2_service
    
- name: Configure instance
  hosts: webserver
  gather_facts: false
  remote_user: ec2-user
  become: yes
  roles:
    - deploy_apache
    
